---
title: "Analysis of Multispecies living ecosystems with cellular automata: Perturbation size"
author: "Group 17"
date: "December 18, 2015"
output: html_document
---


```{r global_options, include=FALSE}

#  date: '`r format(Sys.time(), ''%d %B, %Y'')`'
rm(list=ls())

## Setup code for knitr, we set all global settings here!

knitr::opts_chunk$set(
  ##########################
  eval = TRUE, # ENABLE OR DISABLE ALL CHUNK EVALUATION
  ##########################
  # tidy = TRUE,
  echo = TRUE,
  warning= FALSE, 
  message= FALSE
)

```
This file analyze the effect of perturbation size in the distribution of avalanche sizes.

```{r packages}
# All this packages are requiered

# rmarkdown to generate the document
library(rmarkdown)
# ggplot2 for ploting
library(ggplot2)
# set defualt theme for ggplot
theme_set(theme_bw(14))
# dplyr for data wrangling
library(dplyr)
# poweRlaw for power-law fitting
library(poweRlaw)
# knitr for printing tables
library(knitr)
# data.table for quick file reading with fread function 
library(data.table)

```


```{r extract_parms}

# Function to extract the parameters from the file name 
extract_parms <- function(file){
    parms <- strsplit(file, split = "_")[[1]][-1]
  
  perturb <- strsplit(parms[grep("P", parms)], "-")[[1]][-1]
  perturb.bool <- as.logical(perturb[1])
  perturb.n <- as.numeric(perturb[2])
  
  hierachy <- strsplit(parms[grep("H", parms)], "-")[[1]][-1]
  hierachy.bool <- as.logical(hierachy[1])
  hierachy.n <- as.numeric(hierachy[2])
  
  neighbour.level <- as.numeric(strsplit(parms[grep("N", parms)], "-")[[1]][-1])
  
  update.interaction <- as.logical(strsplit(parms[grep("I", parms)], "-")[[1]][-1])
  
  
  steps <- as.numeric(
        strsplit(parms[grep("S",parms)], "-")[[1]][-1]
  )
     
  
  M <- as.numeric(sub(".csv", "", strsplit(parms[grep("M",parms)], "-")[[1]][-1]))
#   
  return(list(perturb.bool, perturb.n, hierachy.bool, hierachy.n,
              neighbour.level, update.interaction, steps, M))
}
```




####  The following files are used for the analysis. 

```{r read_data, cache = FALSE}

## read files and extract parameters, create a dataframe with one column per parameter

txt_files_avalanches <- list.files("./data/avalanches_all/avalanches_power_law_analysis/")
path_avalanches <- file.path("./data", "avalanches_all",
                            "avalanches_power_law_analysis") 


data_list <- lapply(txt_files_avalanches, function(file, path){
    print(file)
  
  parms.ls <- extract_parms(file)
  p <- file.path(path, file)
  data.raw <- read.csv(p, sep = ",", header = FALSE) 
  
 data <- as.data.frame(t(data.raw)) %>% rename(output = V1)  %>% 
  # this column contains the timestep at which the perturbation took place
  # it just sum the values of the avalanche length
  mutate(
    ava_length = as.numeric(gsub("[[:punct:]]|[[:punct:]] \\d+[[:punct:]]", "", as.character(output))),
    affected_cells = as.numeric(gsub("[[:punct:]]\\d+[[:punct:]]|[[:punct:]]", "", as.character(output))),
                  time = cumsum(ava_length)) 
  
 data$perturb <- parms.ls[[1]]
 data$perturb_n <- parms.ls[[2]]
 data$hierarchy <- parms.ls[[3]]
 data$hierarchy_n <- parms.ls[[4]]
 data$neighbours_level <- parms.ls[[5]]
 data$update <- parms.ls[[6]]
 data$steps <- parms.ls[[7]]
 data$M <- parms.ls[[8]]
 return(data)
}, path = path_avalanches)

avalanches <- do.call(rbind, data_list) 



```



#### Summary of used parameters

```{r}
# print a table with the used perturb size
kable(avalanches %>% select(-ava_length, -time, -affected_cells, -output) %>% distinct() %>% arrange(perturb_n))
  
```



```{r fit_power_law, fig.keep="none", cache=TRUE}

# fit power law to the data calculate a p.value using bootstrap and create the data for the plot

pert <- unique(avalanches$perturb_n)

# loop over the different pertubation sizes (pert)
p2.ls <- lapply(pert, function(p_s, df){
  # subset the avalanches dataframe to select only one pertubation size and remove the first time point because the system is not perturbed yet
  a <- df %>% 
    filter(perturb_n == p_s) %>% 
    filter(time != min(time) & affected_cells != 0)
  
  # create the distribution object with poweRlaw package
  m_m = displ$new(a$affected_cells)
  
  # set initial parameters
  m_m$setPars(2)
  m_m$setXmin(2)
  # calculate parameters
  (est = estimate_xmin(m_m))
  m_m$setXmin(est)
  KS <- est$KS
  (est = estimate_pars(m_m))
  m_m$setPars(est)
  
  
  
  # perform bootstrap
  bs <- bootstrap_p(m_m, no_of_sims=500, threads = 4)
  # get parameters uncertainty
  pars_sd <- sd(bs$bootstraps$pars)
  xmin_sd <- sd(bs$bootstraps$xmin)
  
  # create the data for the plot
  dd <- bind_rows(
    # data points
    plot(m_m) %>% mutate(type = rep("data")),
    # fit
    lines(m_m) %>% mutate(type = rep("powerlaw"))
  ) %>% 
    # add a column with the perturbation size
    mutate(
      perturb_n = rep(p_s)
    )
    
  # create a data.frame with the parameters
  parms <- data.frame(
    "perturb_n" = p_s, 
    "alpha" = m_m$getPars(), 
    "alpha_sd" = pars_sd, 
    "xmin" = m_m$getXmin(), 
    "xmin_sd" = xmin_sd, 
    "KS" = ifelse(is.null(KS), NA, KS), 
    bstrp_pvalue = bs$p)
    

  return(list("df.plot"=  dd, "parms.df" = parms))
}, df = avalanches)


# bind the df.plot data in a single dataframe
p2 <- do.call(rbind, lapply(p2.ls, "[[", 1))

# bind the parms.df in a single dataframe
model.results <- do.call(rbind, lapply(p2.ls, "[[", 2))

 
```



### This is how a power law looks like  (drawn from another dataset)
```{r, fig.keep="none", results="hide"}

# use the moby dick dataset to plot how a power law distribution should look like
data(moby)

.hist <- hist(moby, breaks=max(moby) / 10)
  m_m = displ$new(moby)
  
  
  dd.plot = 
    bind_rows(
    plot(m_m) %>% 
    mutate(group = rep("CDF")),
    dd.hist <- data.frame(x = .hist$mids, y = .hist$counts, group = rep("histogram"))  %>% filter(y != 0)
    )

```

```{r,  fig.height=3, fig.width=6}

  dd.plot %>% ggplot(aes(x, y)) +
  geom_point() +
  scale_y_log10() +
  scale_x_log10() +
  facet_wrap(~group,scales = "free")

```


### Cumulative distribution function and fit
```{r, fig.height=6, fig.width=12}

# plot the CDF with the data and fit
p2 %>%
  filter(type == "data") %>%ggplot(aes(x, y)) +
   geom_point()+
  scale_y_log10() +
  scale_x_log10() +
  facet_wrap(~perturb_n, nrow = 1) +
    geom_line(data = p2 %>% filter(type == "powerlaw"), aes(x, y), color = "red", size = 1.5) +
  xlab("Affected cells") +
  ylab("CDF")
  
```

### Estimated parameters and p-values

```{r}
kable(model.results %>% arrange(perturb_n))
```


